# Generated by Django 4.0.3 on 2022-03-10 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReferenceAircraftType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=4, verbose_name='Nom de code')),
                ('engine_type', models.CharField(choices=[('JET', 'Réacteur'), ('TURBOPROP', 'Turboprop'), ('PISTON', 'Piston')], max_length=9, verbose_name='Type de motorisation')),
                ('number_of_engines', models.PositiveIntegerField(default=0, verbose_name='Nombre de moteurs')),
                ('wake_cat', models.CharField(choices=[('SUPER', 'Super'), ('HEAVY', 'Heavy'), ('MEDIUM', 'Medium'), ('LIGHT', 'Light')], max_length=9, verbose_name='Catégorie de turbulence de sillage')),
                ('max_mass', models.PositiveIntegerField(default=0, verbose_name='Masse max (kg)')),
                ('max_operating_altitude', models.PositiveIntegerField(default=0, verbose_name='Plafond opérationnel (ft)')),
                ('mmo', models.DecimalField(decimal_places=2, default=0, max_digits=3, verbose_name='MMO')),
                ('vmo', models.PositiveIntegerField(default=0, verbose_name='VMO (kt)')),
            ],
            options={
                'verbose_name': 'Types avion de référence',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='FlightPhaseEnvelop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase', models.CharField(choices=[('CLIMB', 'Montée'), ('CRUISE', 'Croisière'), ('DESCENT', 'Descente')], max_length=7, verbose_name='Phase de vol')),
                ('low_altitude_speed', models.PositiveIntegerField(default=0, verbose_name='Vitesse basse altitude (kt)')),
                ('high_altitude_speed', models.PositiveIntegerField(default=0, verbose_name='Vitesse haute altitude (kt)')),
                ('mach_number', models.DecimalField(decimal_places=2, default=0, max_digits=3, verbose_name='Point de Mach')),
                ('aircraft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phases', to='aircrafts.referenceaircrafttype')),
            ],
            options={
                'verbose_name': 'Phase de vol',
                'verbose_name_plural': 'Phases de vol',
                'ordering': ['aircraft', 'phase'],
            },
        ),
        migrations.CreateModel(
            name='AircraftType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=4, verbose_name='Nom de code')),
                ('picture', models.ImageField(blank=True, max_length=251, upload_to='pictures', verbose_name='Photo')),
                ('fullname', models.CharField(blank=True, max_length=250, null=True, verbose_name='Nom complet')),
                ('wikipedia_url', models.URLField(blank=True, null=True, verbose_name='Lien Wikipedia')),
                ('last_update', models.DateTimeField(auto_now=True, verbose_name='Mise à jour')),
                ('reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='synonyms', to='aircrafts.referenceaircrafttype', verbose_name='Type avion de référence')),
            ],
            options={
                'verbose_name': 'Type avion',
                'verbose_name_plural': 'Types avion',
                'ordering': ['code'],
            },
        ),
    ]
