# Generated by Django 4.0.3 on 2022-04-10 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aircrafts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flightphaseenvelop',
            name='high_altitude_rocd',
            field=models.IntegerField(default=0, verbose_name='ROCD (ft/min)'),
        ),
        migrations.AddField(
            model_name='flightphaseenvelop',
            name='low_altitude_rocd',
            field=models.IntegerField(default=0, verbose_name='ROCD (ft/min)'),
        ),
        migrations.AddField(
            model_name='flightphaseenvelop',
            name='mach_rocd',
            field=models.IntegerField(default=0, verbose_name='ROCD (ft/min)'),
        ),
        migrations.AddField(
            model_name='referenceaircrafttype',
            name='performance_parameters',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
