# Generated by Django 4.0.5 on 2022-06-09 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aircrafts', '0003_alter_flightphaseenvelop_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aircrafttype',
            name='version',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Version'),
        ),
        migrations.AlterField(
            model_name='referenceaircrafttype',
            name='version',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Version'),
        ),
    ]
