# Generated by Django 4.0.5 on 2022-06-16 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aircrafts', '0005_aircrafttype_access_counter_aircrafttype_last_access'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aircrafttype',
            name='access_counter',
        ),
        migrations.RemoveField(
            model_name='aircrafttype',
            name='last_access',
        ),
        migrations.CreateModel(
            name='AircraftTypeAccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('aircraft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_logs', to='aircrafts.aircrafttype')),
            ],
            options={
                'verbose_name': "Log d'accès",
                'verbose_name_plural': "Logs d'accès",
                'ordering': ['-date'],
            },
        ),
    ]
