# Generated by Django 4.0.5 on 2022-06-22 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aircrafts', '0006_remove_aircrafttype_access_counter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referenceaircrafttype',
            name='engine_type',
            field=models.CharField(choices=[('JET', 'Réacteur'), ('TURBOPROP', 'Turboprop'), ('PISTON', 'Piston'), ('ELECTRIC', 'Electrique')], max_length=9, verbose_name='Type de motorisation'),
        ),
    ]
