# Generated by Django 4.0.5 on 2022-06-22 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aircrafts', '0007_alter_referenceaircrafttype_engine_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='referenceaircrafttype',
            name='length',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3, verbose_name='Longueur'),
        ),
    ]
