# Generated by Django 4.0.5 on 2022-06-22 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aircrafts', '0008_referenceaircrafttype_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='referenceaircrafttype',
            name='transition_altitude',
            field=models.PositiveIntegerField(default=0, verbose_name='Altitude de transition (ft)'),
        ),
    ]
