# Generated by Django 4.0.5 on 2022-07-01 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aircrafts', '0009_referenceaircrafttype_transition_altitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aircrafttype',
            name='picture',
            field=models.ImageField(blank=True, max_length=251, null=True, upload_to='pictures', verbose_name='Photo'),
        ),
    ]
